### ISSUE TITLE
Add auth to Dockerfile

### ISSUE THREAD

**Issue by conniey** [Azure/azure-mcp#160]
Running MCP server inside docker doesn't work.  Need to pass in a way to auth in image.

**Comment by nicobit** [comment]
I have what is below in docker.compose and authentication is working: 


```yaml
azure_mcp_server:
  image: mcp/azure:latest
  container_name: azure_mcp_server
  ports:
    - "3002:3002"
  environment:
    - AZURE_TENANT_ID=${AZURE_TENANT_ID}
    - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
    - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
    - AZMCP_TRANSPORT=sse
    # - AZMCP_PORT=3002
    - Kestrel__Endpoints__Http__Url=http://0.0.0.0:3002
  restart: unless-stopped
```
Some problem with the port but fixed with "Kestrel__Endpoints__Http__Url=http://0.0.0.0:3002".

With the new version of Docker file I don't think is possible to use anymore AZMCP_TRANSPORT=sse and it could be not clean the way to setup it : SSE is needed to keep the container live and not stop it
