### ISSUE TITLE
Azure MCP Server fails to query Application Insights tables with JSON parsing error

### ISSUE THREAD

**Issue by chris-battle-bunnings** [Azure/azure-mcp#250]
# Azure MCP Server fails to query Application Insights tables with JSON parsing error

## Bug Description

The Azure MCP Server's `azmcp-monitor-log-query` tool consistently fails when querying Application Insights tables (e.g., `AppTraces`) with a JSON parsing error, while the same queries work perfectly in the Azure Portal and other Azure Log Analytics tables work fine through the MCP server.

## Error Details

**Primary Error:**
```
Error querying logs: Error querying workspace: 'e' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
```

**Secondary Error (when using legacy table names):**
```
BadArgumentError, SemanticError - "'order' operator: Failed to resolve table or column expression named 'traces'" (SEM0100)
```

## Environment Information

- **Azure MCP Server Version:** `@azure/mcp@latest` (installed via npx)
- **Client:** Cursor IDE with MCP support
- **Workspace:** Workspace-based Application Insights resource
- **Workspace ID:** `ae51d3eb-6ebc-4867-84a9-dd29aa5fd64f-YouTubeWatcherRG-EAU`
- **Subscription:** `ae51d3eb-6ebc-4867-84a9-dd29aa5fd64f`
- **Resource Group:** `YouTubeWatcherRG`
- **Authentication:** Azure CLI (`az login`) - confirmed working

### What Works ✅

1. **Standard Log Analytics tables:**
   ```
   Tool: azmcp-monitor-log-query
   Parameters:
   - table-name: "FunctionAppLogs" 
   - query: "FunctionAppLogs | order by TimeGenerated desc | take 15"
   Result: Success (returns empty array, but no errors)
   ```

2. **Azure Portal queries:**
   - Same Application Insights workspace
   - Query: `traces | order by timestamp desc | take 15`
   - Result: Returns data successfully

### What Fails ❌

3. **Application Insights tables via MCP:**
   ```
   Tool: azmcp-monitor-log-query
   Parameters:
   - table-name: "AppTraces"
   - query: "AppTraces | order by TimeGenerated desc | take 15"
   Result: Error querying logs: Error querying workspace: 'e' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   ```

4. **Legacy table names:**
   ```
   Tool: azmcp-monitor-log-query  
   Parameters:
   - table-name: "traces"
   - query: "traces | order by timestamp desc | take 15"
   Result: SemanticError - "'order' operator: Failed to resolve table or column expression named 'traces'" (SEM0100)
   ```

### Table Availability Confirmed
Used `azmcp-monitor-table-list` to confirm `AppTraces` exists in the available tables list along with other Application Insights tables (`AppRequests`, `AppExceptions`, `AppDependencies`, etc.).

### Attempted Variations
- Tried both `TimeGenerated` and `timestamp` column names
- Tried with and without `table-name` parameter
- Tried various query formats and complexity levels
- All Application Insights table queries fail with the same error pattern

### Error Analysis
The `'e' is an invalid start of a value` error is a classic JSON parsing error, suggesting:
1. The tool is receiving an unexpected response format from the Application Insights API endpoint
2. There may be authentication/permission issues specific to Application Insights data access
3. The tool might be using wrong API endpoints for workspace-based Application Insights resources

## Expected Behavior

The Azure MCP Server should be able to query Application Insights tables (`AppTraces`, `AppRequests`, etc.) in workspace-based Application Insights resources, just as it successfully queries standard Log Analytics tables.

## Actual Behavior

Application Insights table queries consistently fail with JSON parsing errors, while:
- Standard Log Analytics tables work fine through the same tool
- The same queries work perfectly in Azure Portal
- Authentication is confirmed working for other Azure MCP Server operations

## Impact

This prevents AI agents using the Azure MCP Server from accessing Application Insights telemetry data, which is a core use case for monitoring and troubleshooting applications in Azure.
